export const industries = [
  "Technology", "Marketing", "Finance", "Healthcare", "Education",
  "Consulting", "Design", "Legal", "Real Estate", "Manufacturing",
  "E-commerce", "Media", "Non-profit", "Government", "Other",
];

export const regions = [
  "North America", "Europe", "Asia Pacific", "Middle East", "Africa",
  "Latin America", "Global",
];

export const connectionTypes = [
  "Mentorship", "Partnership", "Collaboration", "Investment", "Freelance",
  "Advisory", "Networking", "Knowledge swap",
];

export const dummyEvents = [
  {
    id: "evt-1",
    title: "SWAAP Tech & Marketing Exchange",
    description: "Quarterly meetup for tech and marketing professionals to swap expertise. Bring your skills, leave with new connections.",
    date: "2025-02-15",
    time: "18:00",
    location: "London, UK",
    type: "In-person",
    industry: "Technology",
    attendees: 84,
    price: 0,
  },
  {
    id: "evt-2",
    title: "AI in Business Networking",
    description: "Explore how AI-driven matchmaking is transforming professional connections. Workshops and networking.",
    date: "2025-02-20",
    time: "14:00",
    location: "Virtual",
    type: "Online",
    industry: "Technology",
    attendees: 256,
    price: 29,
  },
  {
    id: "evt-3",
    title: "Design × Dev Swap Lounge",
    description: "Designers and developers exchange services. Need a logo? Swap with code. Need a landing page? Swap with branding.",
    date: "2025-02-28",
    time: "17:00",
    location: "Berlin, Germany",
    type: "In-person",
    industry: "Design",
    attendees: 42,
    price: 15,
  },
  {
    id: "evt-4",
    title: "Startup Founders Knowledge Swap",
    description: "Founders share lessons on growth, fundraising, and ops. One-on-one swap sessions included.",
    date: "2025-03-05",
    time: "10:00",
    location: "New York, USA",
    type: "Hybrid",
    industry: "Consulting",
    attendees: 120,
    price: 49,
  },
  {
    id: "evt-5",
    title: "Marketing for Developers",
    description: "Devs learn basic marketing; marketers learn basic dev. Structured swap workshops.",
    date: "2025-03-12",
    time: "16:00",
    location: "Virtual",
    type: "Online",
    industry: "Marketing",
    attendees: 189,
    price: 0,
  },
];

export const dummyProfiles = [
  {
    id: "prof-1",
    name: "Alex Chen",
    headline: "Senior Software Engineer | React & Node",
    industry: "Technology",
    region: "Europe",
    expertise: ["Programming", "System Design", "API Development"],
    lookingFor: ["Marketing help", "UI/UX feedback", "Product advice"],
    verified: true,
    connectionCount: 124,
  },
  {
    id: "prof-2",
    name: "Jordan Blake",
    headline: "Growth Marketing Lead | B2B SaaS",
    industry: "Marketing",
    region: "North America",
    expertise: ["Digital Marketing", "Content Strategy", "SEO"],
    lookingFor: ["Dev support for landing pages", "Technical SEO", "Analytics setup"],
    verified: true,
    connectionCount: 89,
  },
  {
    id: "prof-3",
    name: "Samira Okonkwo",
    headline: "Product Designer | UX Research",
    industry: "Design",
    region: "Africa",
    expertise: ["UI/UX", "User Research", "Prototyping"],
    lookingFor: ["Front-end collaboration", "Design systems", "Freelance devs"],
    verified: true,
    connectionCount: 67,
  },
  {
    id: "prof-4",
    name: "Marcus Webb",
    headline: "Founder | EdTech Startup",
    industry: "Education",
    region: "North America",
    expertise: ["Strategy", "Fundraising", "Team building"],
    lookingFor: ["Technical co-founder", "Marketing", "Legal advice"],
    verified: false,
    connectionCount: 43,
  },
  {
    id: "prof-5",
    name: "Yuki Tanaka",
    headline: "Data Scientist | ML & Analytics",
    industry: "Technology",
    region: "Asia Pacific",
    expertise: ["Machine Learning", "Data Pipelines", "Python"],
    lookingFor: ["Business development", "Domain experts", "Deploy ops"],
    verified: true,
    connectionCount: 98,
  },
];

export const dummyUserProfile = {
  id: "user-1",
  name: "Alex Chen",
  email: "alex.chen@example.com",
  headline: "Senior Software Engineer | React & Node",
  industry: "Technology",
  region: "Europe",
  expertise: ["Programming", "System Design", "API Development"],
  lookingFor: ["Marketing help", "UI/UX feedback", "Product advice"],
  bio: "I build scalable web apps and love helping non-technical founders with dev work. Happy to swap coding hours for marketing or design.",
  verified: true,
  connectionCount: 124,
  eventsAttended: 6,
};
